### ISSUE TITLE
Week Two

### ISSUE THREAD

**Issue by CSBCounsel** [KCLegalHackers/CodingForLawyers#4]
# Assignments
- Watch Sessions 1 and 2.
- For new GitHub users, read the Hello World intro to GitHub available [here](https://guides.github.com/activities/hello-world/).

**Comment by bryangw1** [comment]
Session will be on the Second Floor at Think Big at 6:00 pm

**Comment by CSBCounsel** [comment]
If you have any issues getting into Think Big, you can call/text me at 913.439.9631.

**Comment by zmon** [comment]
We are watching https://www.udemy.com/automate/ you will need to sign up.

**Comment by CSBCounsel** [comment]
Hi everyone - looking forward to tonight! There is an event on the second floor, so please come up to the third floor. There is an elevator in the back area of the building. Call me if you have any issues getting in. My number is 913-439-9631..
